version: "3.8"

services:
  app:
    build:
      context: .
    expose:
      - "8080"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-doacoesdb}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-12345678}
      JWT_SECRET: ${JWT_SECRET:-doacoesSecretKey2025SystemSecurityTokenJWT}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10MB}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-10MB}
      UPLOAD_DIR: ${UPLOAD_DIR:-./uploads}
      SERVER_PORT: ${SERVER_PORT:-8080}
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  pgdata:
