version: "3.8"

services:
  app:
    build:
      context: .
    expose:
      - "8080"
    networks:
      - coolify
    environment:
      DATABASE_URL: ${DATABASE_URL:-:jdbc:postgresql://localhost:5432/postgres}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-12345678}
      JWT_SECRET: ${JWT_SECRET:-doacoesSecretKey2025SystemSecurityTokenJWT}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10MB}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-10MB}
      UPLOAD_DIR: ${UPLOAD_DIR:-./uploads}
      SERVER_PORT: ${SERVER_PORT:-8080}
    volumes:
      - ./uploads:/app/uploads

networks:
  coolify:
    external: true
volumes:
  pgdata:
